### ISSUE TITLE
Error relating to BTR during watch mode 

### ISSUE THREAD

**Issue by JamesMilnerUK** [dojo/cli-build-app#244]
**Bug**

![screenshot_20190208_204450](https://user-images.githubusercontent.com/8822075/52717163-5ccd3e80-2f98-11e9-8b13-7434c648aa4f.png)

Package Version: 5.0.1-pre

**Expected behavior:**

Watch mode does not crash

**Actual behavior:**

Watch mode will crash with the error above

**Comment by agubler** [comment]
This seems to be because the manifest plugin that is used, keeps a counter that is incremented when webpack runs and decremented when webpack emits. Before adding the `manifest.json` to the `compilation.assets` the plugin checks that the counter is equal to `0`, i.e. webpack has been run and emitted an equal number of times.

In serve mode the `NoEmitOnErrorsPlugin` is used which during an error build stops webpack from running the `emit` phase, this leaves the counter at a non zero number - meaning that every subsequent build will skip adding the `manifest.json` to the assets as the counter is greater 0.
