### ISSUE TITLE
HMR websocket path should be prefixed

### ISSUE THREAD

**Issue by robagar** [dojo/cli-build-app#277]
**Bug / Enhancement**

The HMR path used to connect to the `dojo build --serve` process should be prefixed by the path used to load the app.

I have a number of web apps, all served by the same host but running behind Nginx.  For development it would be handy to have several `dojo build --serve` processes running.  Each one can have a different port for actually serving files which is cool, but HMR always connects to the same path, `/__webpack_hmr` so they clash.  If that path can be overridden, I could then route it through to the right dojo build process in the nginx config.

All the `dojo build` servers are running behind Nginx, the client sees everything coming from port 80
eg I have two apps `/devices` and `/probe`, each with their own dojo build server.  Nginx forwards requests on port 80 to anything under `/devices` to the one listening to 9998,  anything under `/probe` to 9999. But because both web apps connect to `/__webpack_hmr` I can't forward the HMR requests to the right backend.

So really I want to override the `__webpack_hmr` path the app running in the browser connects to, not the one `dojo build --serve` is listening for.  The devices app should connect to `/devices/__webpack_hmr`, probe to `/probe/_webpack_hmr`. 

I did a bit of digging - it's the _webpack-hot-middleware_ client option `path` that needs setting I believe.

**Comment by agubler** [comment]
@robagar Thanks for raising the issue. I don't believe the issue is that the path is not configurable, but more over that `_webpack_hmr` needs to be loaded relative to the path so that it correctly gets routed through to the running application. At the moment `_webpack_hmr` is loaded from the application root which causes the issue when using with the setup described. 

Will be working on a fix to support your use case this week.

**Comment by agubler** [comment]
@robagar There is a pull request in `@dojo/webpack-contrib` here https://github.com/dojo/webpack-contrib/pull/153 that should support your use case.
