### ISSUE TITLE
Unable to serve the app

### ISSUE THREAD

**Issue by umaar** [dojo/cli-build-app#34]
If I run `dojo build`, it works well, but if I run `dojo build -s -p 9999` to serve the app, I see it hangs. I tried with two versions of `cli-build-app`, I tried the master branch and also the latest published NPM version.

Here are my current versions :

```
dojo version

The currently installed groups are:

build (@dojo/cli-build-app) 0.1.0
create (@dojo/cli-create-app) 0.2.1
test (@dojo/cli-test-intern) 0.2.1

You are currently running @dojo/cli 0.2.0
```

The app I tried this in is one created with `dojo create app -n testing`. Also ran `rm -rf node_modules/@dojo/cli-build-webpack` before continuing.

**Comment by mwistrand** [comment]
Thanks for filing the issue, @umaar. The problem is `dojo build -s` just starts the server when it really ought to at least build once in the process. So the server is actually listening on port `9999`, but as nothing has been built, the directory it's trying to serve (`/output/{mode}`) doesn't actually exist yet.
