### ISSUE TITLE
Using the `-watch` arg does not include image files used in css.

### ISSUE THREAD

**Issue by tomdye** [dojo/cli-build-app#44]
When testing usage of cli build app with the animations tutorial I found that it does not bundle up `png` files sourced from the `css` files.
This works fine without the `watch` command.

Output example below:
![screenshot 2018-01-22 17 21 53](https://user-images.githubusercontent.com/814453/35235818-234f0b24-ff9d-11e7-856a-1744b606e688.png)

**Comment by mwistrand** [comment]
Fortunately, this does not happen with the memory watch, and only rears its head when manually deleting the `output/{mode}` directory with the file watch. Now I just need to figure out how to force changes to pick up on the image files.

**Comment by mwistrand** [comment]
After further investigation, this is working as expected. During compilation, any images that are referenced by CSS files are included by the `file-loader`. When the CSS files that import images do not change, the `file-loader` is never called upon since any images it would bundle have already been processed and copied to the `config.output` directory.

**Comment by tomdye** [comment]
@mwistrand thanks for your investigation, I ran it all again today and now it's working as expected. I can not explain why it was not loading / showing images yesterday. It was not just the console output, but the page did not include images. The same was happening for me with a new app and the spinning dojo logo. But today that works too. Odd

**Comment by mwistrand** [comment]
@tomdye To be clear, it is possible to reproduce the issue if you 1) `dojo build -w -m dev`, 2) delete the `output/dev/` directory, and then 3) change a widget file or even the relevant CSS file _without modifying the image's URL or presence_. Since the compiler does not observe the output directory, it has no idea that the image has been deleted, and if the relevant section of the CSS file does not change, then the compiler will not know that it needs to re-bundle the image. However, if you comment out the `background: url(...)`, save, re-add the `background: url(...)`, and save again, the compiler will re-add the image to the output directory.
